apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-active
  namespace: argo-bluegreen
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: bluegreen.k8s.orb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-active-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-preview
  namespace: argo-bluegreen
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: preview.bluegreen.k8s.orb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-preview-svc
            port:
              number: 80
