apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-rollout
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flask-app
        image: myflask:v1.2  # <--- 改成你推到仓库的镜像repo:tag
        ports:
        - containerPort: 5000

  strategy:
    canary:
      stableService: flask-stable-svc
      canaryService: flask-canary-svc
      steps:
        - setWeight: 20
        - pause:            # 指明 pause，但不设 duration，表示无限等待
            duration: 0     # 或者干脆直接省略 duration
        - setWeight: 100
