apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-rollout-bluegreen
  namespace: argo-bluegreen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flask-app
        image: myflask:v2.4.5  # <--- 改成你推到仓库的镜像repo:tag
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

  strategy:
    blueGreen:
      activeService: flask-active-svc
      previewService: flask-preview-svc
      autoPromotionEnabled: false
      steps:
      - name: pause-before-promotion
        pause: {}
      - name: promote
        setWeight: 100
